W1202 12:09:35.535000 2847991 site-packages/torch/distributed/run.py:793] 
W1202 12:09:35.535000 2847991 site-packages/torch/distributed/run.py:793] *****************************************
W1202 12:09:35.535000 2847991 site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1202 12:09:35.535000 2847991 site-packages/torch/distributed/run.py:793] *****************************************
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
    func_return = func(*args, **kwargs)  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group

  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)    
return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
Traceback (most recent call last):
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 708, in <module>
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    main(
  File "/home/charlie/skip-residual/gpt-fast/benchmark.py", line 526, in main
    func_return = func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
    ProcessGroupManager(tensor_parallel_world_size=tp_world_size, pipeline_parallel_world_size=pp_world_size)
  File "/home/charlie/skip-residual/gpt-fast/gpt_fast/parallel.py", line 30, in __init__
    torch.distributed.init_process_group(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1613, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1845, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
torch.distributed.DistNetworkError: failed to recv, got 0 bytes
W1202 12:24:39.775000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848059 closing signal SIGTERM
W1202 12:24:39.776000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848060 closing signal SIGTERM
W1202 12:24:39.776000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848061 closing signal SIGTERM
W1202 12:24:39.777000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848062 closing signal SIGTERM
W1202 12:24:39.777000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848063 closing signal SIGTERM
W1202 12:24:39.778000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848064 closing signal SIGTERM
W1202 12:24:39.778000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2848066 closing signal SIGTERM
E1202 12:24:39.955000 2847991 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 6 (pid: 2848065) of binary: /home/charlie/anaconda3/envs/gpt-fast/bin/python
Traceback (most recent call last):
  File "/home/charlie/anaconda3/envs/gpt-fast/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/charlie/anaconda3/envs/gpt-fast/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
benchmark.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-12-02_12:24:39
  host      : mk-xii-14.cloud.together.ai
  rank      : 14 (local_rank: 6)
  exitcode  : 1 (pid: 2848065)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
